### ISSUE TITLE
Remove CreatedBy field in https://ds-ec2.scraperwiki.com/3zarzzv/0zftw6fzkjxommp/cgi-bin/csv/ors_frw.csv

### ISSUE THREAD

**Issue by takavarasha** [luiscape/hdxscraper-ors#9]

**Comment by luiscape** [comment]
Done. Here are the results: https://data.hdx.rwlabs.org/dataset/country-framework/resource/735b3f3a-eef6-4eb4-8b43-9307bac3177c
